production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        # consistency: :strong
        # identity_map_enabled: true

development:
  clients:
    default:
      database: locomotiveapp_development
      hosts:
        - db:27017
      options:
  options:
test:
  clients:
    default:
      database: locomotiveapp_test
      hosts:
        - db:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
